FROM node:22-alpine AS deps

WORKDIR /app
COPY package*.json ./
RUN npm install

FROM node:22-alpine AS runner

WORKDIR /app
ENV NODE_ENV=development
ENV NEXT_PUBLIC_API_URL=http://localhost:8000
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]
